version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.gradle.build-scan
    versions:
    - 3.5.1
    - 3.5.2
    - "3.6"
  - dependency-name: com.tngtech.archunit:archunit
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
  - dependency-name: com.netflix.nebula:gradle-dependency-lock-plugin
    versions:
    - 11.1.2
